### ISSUE TITLE
Readme.md need  more editing?

### ISSUE THREAD

**Issue by Randrianasulu** [oyvindln/ld-decode#73]
At least I tried to copy some text to our mail-list (in search for cheap 10 bit VHS capture solution. Can this project deal with just normal video signal capture from standard video outputs?) and run into something looking like  cut phrase.

"The gen chroma scrips will use decoded .tbc files and generate standard video files by default a lossless, interlaced top field first and high-bitrate (roughly 70-100 Mb/s) FFV1 codec video which, which although ideal for archival and further processing."

does this mean "  (...), but badly supported as-is for editing"?

I am sort-of very beginner level (forever beginner ..)  developer, currently fixing and breaking cinelerra-gg (video editor/NLE), so surprizing choppines of ffv1 playback is something I saw with my own eyes.

**Comment by harrypm** [comment]
@Randrianasulu 

For analogue tapes, FM RF capture and software decoding is the best way to go for correction and preservation.

For CVBS sources you can use [CVBS-Decode](https://github.com/oyvindln/vhs-decode/wiki/CVBS-Composite-Decode) but it's not going to give anywhere near the results of VHS-Decode this is only ideal for live sources like cameras or digital formats, or analogue ones that have already been through a hardware TBC of some forum (so the whole point of the powerful software TBC in vhs-decode is lost and it costs more space in terms of RF capture)

FFV1 is **not supported by Avid Pro Tools/DaVinchi Resolve/Adobe Suite/Final Cut** hence why it's pretty much disregarded for editing and re-muxing to V210/ProRes HQ (and setting the CLAP/Colr Atom data in [amcdx-video-patcher](https://mogurenko.com/2021/01/29/amcdx-video-patcher-v0-6-7/) properly after the fact) 

It's meant more so for tossing into tools like StaxRip etc using a deinterlacer QTGMC/IVTC than editing in an NLE directly.

(FFV1 is supported in Lossless Cut but at potato render quality.)

The issue is also the output from the gen_chroma_vid.sh script is not flagged for interlacing properly this is a limit of FFmpeg but re-muxing fixes this issue hence why this command is added.

`ffmpeg -hide_banner -i "$1.mkv" -vf setfield=tff -flags +ilme+ildct -c:v prores -profile:v 3 -vendor apl0 -bits_per_mb 8000 -quant_mat hq -mbs_per_slice 8 -pixel_format yuv422p10lep -color_range tv -color_primaries bt709 -color_trc bt709 -colorspace bt709 -c:a s24le -vf setdar=4/3,setfield=tff "$1_ProResHQ.mov"
`

The wiki is pretty extensive but post-processing docs are being worked on.
